import { ArrowDown, ArrowUpRight, Code2, ExternalLink, Mail } from "lucide-react";
import { Header } from "@/components/header";
import { projects } from "@/data/projects";

const mono = "font-[family-name:var(--font-mono)] text-[11px] font-medium uppercase tracking-[0.1em]";
const featuredProjects = projects.slice(0, 4);
const additionalProjects = projects.slice(4);

export default function Home() {
  return <>
    <Header />
    <main id="inicio">
      <section className="bg-[#f7f7f7] py-20 sm:py-24">
        <div className="mx-auto grid w-full max-w-6xl gap-16 px-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)] lg:items-end">
          <div>
            <p className={`${mono} mb-5 flex items-center gap-2 text-zinc-600`}><span className="h-2 w-2 rounded-full bg-[#7396c8]" />Disponível para oportunidades</p>
            <h1 className="max-w-4xl text-balance text-[clamp(2.6rem,4.5vw,4.65rem)] font-bold leading-[1.02] tracking-[-.06em] text-zinc-950">Produtos web, APIs e automações.</h1>
            <p className="mt-7 max-w-2xl text-pretty text-base leading-7 text-zinc-600 sm:text-lg">Sou Lucas Pinheiro, desenvolvedor Full Stack. Crio interfaces, serviços e automações com código organizado, validações e foco na experiência de uso.</p>
            <div className="mt-9 flex flex-wrap gap-3"><a className="inline-flex items-center gap-2 rounded-md bg-[#7396c8] px-5 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#5f80b0]" href="#projetos">Ver projetos <ArrowDown size={17} /></a><a className="inline-flex items-center gap-2 rounded-md border border-zinc-300 px-5 py-3 text-sm font-bold text-zinc-900 transition hover:border-[#b8cbe5] hover:bg-white" href="https://github.com/lucasppinheiro" target="_blank" rel="noreferrer"><Code2 size={17} />GitHub</a></div>
            <p className="mt-10 max-w-3xl border-t border-zinc-200 pt-4 font-[family-name:var(--font-mono)] text-xs text-zinc-500">React · TypeScript · Node.js · .NET · Java · Python</p>
          </div>
          <aside className="border-l-2 border-[#7396c8] pl-6 lg:mb-1" aria-label="Principais frentes de atuação">
            <p className={`${mono} mb-6 text-zinc-500`}>Principais frentes</p>
            <div className="space-y-5"><div><h2 className="text-base font-bold tracking-[-.02em] text-zinc-950">Aplicações web</h2><p className="mt-1 text-sm leading-6 text-zinc-600">Interfaces responsivas e fluxos completos.</p></div><div><h2 className="text-base font-bold tracking-[-.02em] text-zinc-950">APIs e integrações</h2><p className="mt-1 text-sm leading-6 text-zinc-600">Serviços, autenticação e dados conectados.</p></div><div><h2 className="text-base font-bold tracking-[-.02em] text-zinc-950">Automação e qualidade</h2><p className="mt-1 text-sm leading-6 text-zinc-600">Validações, testes e rotinas confiáveis.</p></div></div>
          </aside>
        </div>
      </section>
      <section id="projetos" className="bg-white py-20 sm:py-24"><div className="mx-auto w-full max-w-6xl px-6"><div className="mb-11 flex max-w-3xl flex-col gap-5"><p className={`${mono} flex items-center gap-2 text-zinc-600`}><span className="h-2 w-2 rounded-full bg-[#7396c8]" />Projetos selecionados</p><h2 className="text-balance text-4xl font-bold tracking-[-.055em] text-zinc-950 sm:text-5xl">O que eu construí</h2><p className="max-w-xl text-zinc-600">Quatro projetos para mostrar produto, back-end, dados e qualidade. Cada um tem código aberto e, quando disponível, uma demonstração online.</p></div><div className="grid gap-4 md:grid-cols-2">{featuredProjects.map((project) => <article className="group flex min-h-80 flex-col rounded-xl border border-zinc-200 bg-zinc-50 p-6 transition hover:-translate-y-1 hover:border-[#b8cbe5] hover:bg-white hover:shadow-lg hover:shadow-zinc-200/50" key={project.name}><p className={`${mono} text-zinc-500`}>{project.category}</p><h3 className="mt-3 text-xl font-bold tracking-[-.04em] text-zinc-950">{project.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{project.description}</p><ul className="mt-5 flex flex-wrap gap-2">{project.stack.map((item) => <li className="rounded bg-white px-2.5 py-1 font-[family-name:var(--font-mono)] text-[11px] text-zinc-600 ring-1 ring-zinc-200" key={item}>{item}</li>)}</ul><div className="mt-auto flex gap-5 pt-7 text-sm font-bold text-[#5f80b0]">{project.demo && <a className="inline-flex items-center gap-1 hover:text-[#47688f]" href={project.demo} target="_blank" rel="noreferrer">Demonstração <ArrowUpRight size={16} /></a>}<a className="inline-flex items-center gap-1 hover:text-[#47688f]" href={project.repository} target="_blank" rel="noreferrer">Código <Code2 size={16} /></a></div></article>)}</div><div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-zinc-200 pt-5 text-sm"><span className="font-semibold text-zinc-700">Outros projetos:</span>{additionalProjects.map((project) => <a className="font-semibold text-zinc-600 hover:text-[#5f80b0]" href={project.repository} target="_blank" rel="noreferrer" key={project.name}>{project.name} <ArrowUpRight className="inline" size={14} /></a>)}</div></div></section>
    </main>
    <footer id="contato" className="bg-zinc-800 py-14 text-white sm:py-16"><div className="mx-auto grid w-full max-w-6xl gap-12 px-6 md:grid-cols-[1.25fr_.75fr] md:items-end"><div><p className={`${mono} flex items-center gap-2 text-zinc-300`}><span className="h-2 w-2 rounded-full bg-[#a8c0e0]" />Contato</p><h2 className="mt-4 text-balance text-4xl font-bold tracking-[-.055em] sm:text-5xl">Vamos falar sobre uma oportunidade?</h2><p className="mt-4 max-w-xl leading-7 text-zinc-300">Estou disponível para oportunidades em desenvolvimento de software e projetos em que eu possa contribuir de ponta a ponta.</p></div><div className="space-y-7 md:justify-self-end"><div><p className={`${mono} mb-3 text-zinc-400`}>E-mail</p><a className="inline-flex whitespace-nowrap items-center gap-2 border-b border-[#a8c0e0] pb-2 text-sm font-semibold text-white transition hover:text-[#d4e1f2]" href="mailto:lucas.gabrielpnr@gmail.com"><Mail className="shrink-0 text-[#b8cbe5]" size={17} />lucas.gabrielpnr@gmail.com</a></div><div><p className={`${mono} mb-3 text-zinc-400`}>Perfis</p><div className="flex gap-5 text-sm font-semibold"><a className="inline-flex items-center gap-1 text-zinc-200 transition hover:text-[#b8cbe5]" href="https://www.linkedin.com/in/lucaspinheirodev" target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={14} /></a><a className="inline-flex items-center gap-1 text-zinc-200 transition hover:text-[#b8cbe5]" href="https://github.com/lucasppinheiro" target="_blank" rel="noreferrer">GitHub <ExternalLink size={14} /></a></div></div></div></div><div className="mx-auto mt-12 w-full max-w-6xl border-t border-zinc-600 px-6 pt-5 text-xs text-zinc-400">© 2026 Lucas Pinheiro</div></footer>
  </>;
}
